# Linear Algebra

In [1]:
# Import libraries
import numpy as np

In [2]:
# dot product of two matrices 
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(f'Array1 : {arr1}\nArray 2: {arr2}')
print('------------------------------')
dot_arr = np.dot(arr1, arr2)
print(f'dot product of array1 and array2 : {dot_arr}')

Array1 : [1 2 3 4]
Array 2: [5 6 7 8]
------------------------------
dot product of array1 and array2 : 70


The dot product of two arrays is calculated using the np.dot() function.
The dot product of two arrays is the sum of the products of the corresponding elements of the two arrays. Here is the formula for the dot product of two arrays:

Here is an example in mathematical notation:

  
 

Here we have two arrays, [1, 2, 3] and [4, 5, 6], and the dot product is 32. We first transform the arrays into vectors and then multiply the corresponding elements and sum the results.

In [4]:
# create a matrix
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print(f'Matrix : \n {matrix}')

Matrix : 
 [[1 2]
 [3 4]
 [5 6]]


In [9]:
# matrix using arange
matrix =np.arange(1, 10).reshape(3, 3)
print(f'Matrix : \n {matrix}')

Matrix : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# matix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
print(f'Matrix 1 : \n {matrix1}\nMatrix 2: \n {matrix2}')
print('-----------------------------') 
matrix_mul = np.matmul(matrix1, matrix2)
print(f'Matrix multiplication of matrix1 and matrix2 : \n {matrix_mul}')

Matrix 1 : 
 [[1 2]
 [3 4]]
Matrix 2: 
 [[5 6]
 [7 8]]
-----------------------------
Matrix multiplication of matrix1 and matrix2 : 
 [[19 22]
 [43 50]]


# Matrix Multiplication
matrix multiplication is calculated using the np.matmul() function.
Matrix multiplication is a binary operation that takes two matrices as inputs and produces another matrix as output. The number of columns in the first matrix must be equal to the number of rows in the second matrix for the multiplication to be defined.
Here is the formula for matrix multiplication:


Where A is an m x n matrix, B is an n x p matrix, and C is an m x p matrix. The element C[i, j] is the dot product of the i-th row of A and the j-th column of B.

Here is an example in mathematical notation:

  
  
  
 

Here we have two 2 x 2 matrices, and the result of the matrix multiplication is another 2 x 2 matrix.

Matrix multiplication also known as the dot product of two matrices.

In [12]:
# inverse of a matrix 
matrix = np.array([[1, 2], [3, 4]])
print(f'Matrix : \n {matrix}')
print('-----------------------------') 
matrix_inv = np.linalg.inv(matrix)
print(f'Inverse of matrix : \n {matrix_inv}')

Matrix : 
 [[1 2]
 [3 4]]
-----------------------------
Inverse of matrix : 
 [[-2.   1. ]
 [ 1.5 -0.5]]


The inverse of a matrix is calculated using the np.linalg.inv() function.
The inverse of a matrix is a matrix that, when multiplied by the original matrix, results in the identity matrix. The inverse of a matrix A is denoted as A^(-1).
The inverse of a matrix A is defined as the matrix A^(-1) such that A^(-1) * A = A * A^(-1) = I, where I is the identity matrix.
Here is the formula for the inverse of a matrix:

 

Where det(A) is the determinant of matrix A and adj(A) is the adjugate of matrix A.

Here is an example in mathematical notation of Identy matrix:

 

Here we have a 3 x 3 identity matrix, where the diagonal elements are 1 and all other elements are 0.

### Determinant of a Matrix
Here is mathematical notation of Determinant matrix:

 

Where a, b, c, and d are the elements of the matrix.

Here we have a 2 x 2 matrix, and the determinant is calculated as ad - bc. For a 2 x 2 matrix, the determinant is the product of the diagonal elements minus the product of the off-diagonal elements. Example, for matrix [[1, 2], [3, 4]], the determinant is 1 * 4 - 2 * 3 = 4 - 6 = -2 as shown here:

 

### Adjugate of a Matrix
Here is the Adjucate matrix example:

 

where a, b, c, and d are the elements of the matrix.

### Inverse of a Matrix
Let's see how to calculate the inverse of a matrix in mathematical notation. Here we have a 2 x 2 matrix [[1, 2], [3, 4]], and the inverse is calculated as follows:

 
 
 
 
  
 

In [13]:
# determinant of matrix
matrix = np.array([[1, 2], [3, 4]])
print(f'Matrix : \n {matrix}')
print('-----------------------------') 
matrix_det = np.linalg.det(matrix)
print(f'Determinant of matrix : \n {matrix_det}')

Matrix : 
 [[1 2]
 [3 4]]
-----------------------------
Determinant of matrix : 
 -2.0000000000000004


In [15]:
# eigenvalues and eigenvectors of a matrix
matrix = np.array([[1,2],[3,4]])
print(f'Matrix : \n {matrix}')
print('-----------------------------') 
matrix_eig = np.linalg.eig(matrix)
print(f'Eigenvalues and eigenvectors of matrix : \n {matrix_eig}')


Matrix : 
 [[1 2]
 [3 4]]
-----------------------------
Eigenvalues and eigenvectors of matrix : 
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


1- Eigenvalues and eigenvectors of a matrix are calculated using the np.linalg.eig() function.
2- Eigenvalues and eigenvectors are properties of square matrices that describe how the matrix behaves when multiplied by a vector.
3- The eigenvectors of a matrix are the vectors that remain in the same direction after the matrix transformation, while the eigenvalues are the scaling factors by which the eigenvectors are stretched or compressed.
4- The eigenvectors and eigenvalues of a matrix are used in various applications, such as principal component analysis (PCA) and solving differential equations.