# Utility Functions

In [1]:
# Import Libraries
import numpy as np

In [3]:
# sort an array
arr = np.array([1, 2, 0, 5, 4, 3])
print(f'Array : {arr}')
print('----------------------') 
sorted_arr = np.sort(arr)
print(f'sorted Array : {sorted_arr}')

Array : [1 2 0 5 4 3]
----------------------
sorted Array : [0 1 2 3 4 5]


In [4]:
# sort a 2D array 
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(f'Array : {arr}')
print('----------------------') 
sorted_arr = np.sort(arr)
print(f'sorted Array : {sorted_arr}')
print('----------------------')

Array : [[3 2 4]
 [5 0 1]]
----------------------
sorted Array : [[2 3 4]
 [0 1 5]]
----------------------


In [8]:
# sort a 2D array by column
arr = np.array([[3, 2, 4], [5, 0, 1], [6, 8, 7]])
print(f'Array :\n {arr}')
print('----------------------') 
sorted_arr = np.sort(arr, axis=1)
print(f'sorted Array :\n {sorted_arr}')
print('----------------------')

Array :
 [[3 2 4]
 [5 0 1]
 [6 8 7]]
----------------------
sorted Array :
 [[2 3 4]
 [0 1 5]
 [6 7 8]]
----------------------


In [9]:
# sort a 2D array by row
matrix = np.array([[6, 5, 4], [3, 2, 1], [9, 8, 7]])
print(f"matrix:\n{matrix}")
print("---------------------------------------------------------")
sorted_matrix = np.sort(matrix, axis=1) # sort by row
print(f"sorted matrix by row:\n{sorted_matrix}")

matrix:
[[6 5 4]
 [3 2 1]
 [9 8 7]]
---------------------------------------------------------
sorted matrix by row:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [10]:
# save an array to a file
arr = np.array([1, 2, 3, 4, 5])
print(f"array: {arr}")
print("---------------------------------------------------------")
np.save("array.npy", arr) # save the array to a file

array: [1 2 3 4 5]
---------------------------------------------------------


In [12]:

# limit values within a range
arr = np.array([1, 2, 3, 4, 5])
print(f"array: {arr}")
print("---------------------------------------------------------")
clip_arr = np.clip(arr, 2, 4) # limit values between 2 and 4
print(f"clipped array: {clip_arr}")

array: [1 2 3 4 5]
---------------------------------------------------------
clipped array: [2 2 3 4 4]
