# Array Manipulation on data

In [26]:
# Import Libraries

import numpy as np

In [27]:
# create an array
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [28]:
# create 2D array
b=np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [29]:
b1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
# create an array with zeros
c = np.zeros((2, 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
# create array with ones
d = np.ones((2, 3)) 
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
# create array empty
f = np.empty((2, 6))
print(f)

[[1.23659685e-311 2.81617418e-322 0.00000000e+000 0.00000000e+000
  0.00000000e+000 1.58817677e-052]
 [4.46535002e-090 1.16345882e+165 2.34121652e-057 4.12060206e-033
  6.48224659e+170 4.93432906e+257]]


In [33]:
# create array with range
g = np.arange(10)
print(g)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
g1 = np.arange(1, 10)
print(g1)

[1 2 3 4 5 6 7 8 9]


In [35]:
g2 = np.arange(1, 10, 2)
print(g2)
print(g2.dtype)

[1 3 5 7 9]
int64


In [36]:
# create array with a arange and a step as float
g3 = np.arange(2, 10, 2, dtype=float)
print(g3)
print(g3.dtype)

[2. 4. 6. 8.]
float64


In [37]:
# with a range and step as float
h = np.arange(1, 10, 0.5)
print(h)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [38]:
# datatype for the array
print(h.dtype)

float64


In [39]:
# with a range and a number of elements evenly spaced
i = np.linspace(0, 12, 5) # 5 elements between 0 and 10
print(i)

[ 0.  3.  6.  9. 12.]


In [40]:
# reshape an array
j = i.reshape(5,1)
print(j)
print(j.shape)

[[ 0.]
 [ 3.]
 [ 6.]
 [ 9.]
 [12.]]
(5, 1)


In [44]:
# reshape an array 
arr = np.array([1, 2, 3, 4, 5,6,7,8])
print(f'array before: {arr}')

array before: [1 2 3 4 5 6 7 8]


In [45]:
reshaped_arr = arr.reshape((2, 4))
print(f"array after reshaping:\n{reshaped_arr}")

array after reshaping:
[[1 2 3 4]
 [5 6 7 8]]


In [47]:
# transpose an array
arr = np.array([[1,2, 3],[4, 5, 6]])
print(f'array before: \n{arr}')

array before: 
[[1 2 3]
 [4 5 6]]


In [48]:
# transpose an array
arr = np.array([[1,2, 3],[4, 5, 6]])
print(f'array before: \n {arr}')
print('-----------------------')
transpose_arr = arr.transpose()
print(f'array after transposing: \n {transpose_arr}')

array before: 
 [[1 2 3]
 [4 5 6]]
-----------------------
array after transposing: 
 [[1 4]
 [2 5]
 [3 6]]


In [49]:
# flatten a multi-dimensional array  
arr = np.array([[1,2, 3],[4, 5, 6]])
print(f'array before: \n {arr}')
print('-----------------------')
flatten_arr = arr.flatten()
print(f'array after flattening: \n {flatten_arr}')
print(f'array after flattening shape: \n {flatten_arr.shape}')

array before: 
 [[1 2 3]
 [4 5 6]]
-----------------------
array after flattening: 
 [1 2 3 4 5 6]
array after flattening shape: 
 (6,)


In [50]:
# repeat elements of an array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print('-----------')
repeat_arr = np.repeat(arr, 3) # repeat each element 3 times
print(f'repeated array: \n {repeat_arr}')

[1 2 3 4 5]
-----------
repeated array: 
 [1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [51]:
# construct an array by repeating it
arr = np.array([1, 2, 3])
print(f"array before: {arr}")
print("---------------------------------------------------------")
tiled_arr = np.tile(arr, 3) # repeat the array 3 times
print(f"tiled array:\n{tiled_arr}")

array before: [1 2 3]
---------------------------------------------------------
tiled array:
[1 2 3 1 2 3 1 2 3]
