# 2- Joining, Spliting and Modifying Arrays

In [2]:
import numpy as np

In [4]:
# concatenate arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(f'Array1: {arr1}')
print(f'Array2: {arr2}')
print('------------------')

concatenate_arr = np.concatenate((arr1, arr2))
print(f'Concatenated array: \n {concatenate_arr}')

Array1: [1 2 3]
Array2: [4 5 6]
------------------
Concatenated array: 
 [1 2 3 4 5 6]


. concatenate() function is used to join arrays along an existing axis which means joining arrays along the existing axis.
### Stacking vs. Concatenation
. Stacking is a general concept that refers to joining two or more arrays along a new axis.                         
.  Concatenation is a specific case of stacking that refers to joining arrays along an existing axis.                                     
. Stacking can be done along different axes, while concatenation is limited to joining arrays along the existing axes.

In [7]:
# Stack arrays 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(f'Array1: {arr1} \nArray2: {arr2}')
print('----------------------------------------------------')
stack_arr = np.stack((arr1, arr2))
print(f'Stacked array: \n {stack_arr}')

Array1: [1 2 3] 
Array2: [4 5 6]
----------------------------------------------------
Stacked array: 
 [[1 2 3]
 [4 5 6]]


In [9]:
#  Vertically Stack arrays 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(f'Array1: {arr1} \nArray2: {arr2}')
print('----------------------------------------------------')
vstack_arr = np.vstack((arr1, arr2))
print(f'Vertically Stacked array: \n {vstack_arr}')

Array1: [1 2 3] 
Array2: [4 5 6]
----------------------------------------------------
Vertically Stacked array: 
 [[1 2 3]
 [4 5 6]]


In [10]:
# Horizontal stack arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(f'Array1: {arr1} \nArray2: {arr2}')
print('----------------------------------------------------')
hstack_arr = np.hstack((arr1, arr2))
print(f'Horizontally Stacked array: \n {hstack_arr}')

Array1: [1 2 3] 
Array2: [4 5 6]
----------------------------------------------------
Horizontally Stacked array: 
 [1 2 3 4 5 6]


In [14]:
# Split and array into sub_array
arr = np.array([1, 2, 3, 4, 5, 6,])
print(f'Array befor: {arr}')
print('----------------------------------------------------')
split_arr = np.split(arr , 3) # split the array into 3 sub_arrays
print(f'Split arrays: \n {split_arr}')

Array befor: [1 2 3 4 5 6]
----------------------------------------------------
Split arrays: 
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [16]:
# Delete element from array
arr = np.array([1, 2, 3, 4, 5, 6,])
print(f'Array befor: {arr}')
print('----------------------------------------------------')
delete_arr = np.delete(arr, 2) # delete the element from array(3rd_element)
print(f'Deleted array: \n {delete_arr}')

Array befor: [1 2 3 4 5 6]
----------------------------------------------------
Deleted array: 
 [1 2 4 5 6]


In [18]:
# Indexing of arrays
arr = np.array([1, 2, 3, 4, 5, 6,])
print(f'Array: {arr}')
print('----------------------------------------------------')
print(f'Elementat index 0: {arr[0]}')
print(f'Elementat index 2: {arr[2]}')
print(f'Elementat index -1: {arr[-1]}')

Array: [1 2 3 4 5 6]
----------------------------------------------------
Elementat index 0: 1
Elementat index 2: 3
Elementat index -1: 6


In [21]:
# indexing of 2D arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(f"array:\n{arr}")
print("---------------------------------------------------------")
print(f"element at row 1, column 2: {arr[1, 2]}")
print(f"element at row 0, column 2: {arr[0, 2]}")

array:
[[1 2 3]
 [4 5 6]]
---------------------------------------------------------
element at row 1, column 2: 6
element at row 0, column 2: 3


In [23]:
# Slicing of arrays
arr = np.array([1, 2, 3, 4, 5, 6,])
print(f'Array: {arr}')
print('----------------------------------------------------')
print(f'Slicing array: \n {arr[1:4]}')
print(f'Slicing array: \n {arr[1:]}')
print(f'Slicing array: \n {arr[:5]}')
print(f'Slicing array: \n {arr[:-2]}')

Array: [1 2 3 4 5 6]
----------------------------------------------------
Slicing array: 
 [2 3 4]
Slicing array: 
 [2 3 4 5 6]
Slicing array: 
 [1 2 3 4 5]
Slicing array: 
 [1 2 3 4]


In [20]:
# slicing array in 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Array: \n {arr}')
print('----------------------------------------------------')
print(f'Slicing array: \n {arr[1:2, 1:3]}')
print(f'Slicing array: \n {arr[1:2, :]}')
print(f'Slicing array: \n {arr[:, 1:3]}')
print(f'Slicing array: \n {arr[:, :]}')

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------------------
Slicing array: 
 [[5 6]]
Slicing array: 
 [[4 5 6]]
Slicing array: 
 [[2 3]
 [5 6]
 [8 9]]
Slicing array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
# Insert elements into an array
arr = np.array([1, 2, 3, 4, 5, 6,])
print(f'Array befor: {arr}')
print('----------------------------------------------------')
insert_arr = np.insert(arr, 2, 10) # insert the element into array(3rd_element)
print(f'Inserted array: \n {insert_arr}')

Array befor: [1 2 3 4 5 6]
----------------------------------------------------
Inserted array: 
 [ 1  2 10  3  4  5  6]


In [25]:
# Append elements into an array
arr = np.array([1, 2, 3, 4, 5, 6,])
print(f'Array befor: {arr}')
print('----------------------------------------------------')
append_arr = np.append(arr, 10) # append the element into array
print(f'Appended array: \n {append_arr}')

Array befor: [1 2 3 4 5 6]
----------------------------------------------------
Appended array: 
 [ 1  2  3  4  5  6 10]


In [27]:
# Update elements in an array
arr = np.array([1, 2, 3, 4, 5, 6,])
print(f'Array befor: {arr}')
print('----------------------------------------------------')
update_arr = np.insert(arr, 4, 10) # insert the element into array(3rd_element)
print(f'Updated array: \n {update_arr}')

Array befor: [1 2 3 4 5 6]
----------------------------------------------------
Updated array: 
 [ 1  2  3  4 10  5  6]
